"""empty message

Revision ID: 19095257d787
Revises: 4ec511dac1a4
Create Date: 2015-05-02 14:24:50.390287

"""

# revision identifiers, used by Alembic.
revision = '19095257d787'
down_revision = '4ec511dac1a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagecounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagecounts')
    ### end Alembic commands ###
