"""empty message

Revision ID: 1c49044e441e
Revises: None
Create Date: 2015-03-21 23:24:10.024605

"""

# revision identifiers, used by Alembic.
revision = '1c49044e441e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
