"""empty message

Revision ID: 1d6ddd54e6ae
Revises: 303383e2e457
Create Date: 2015-04-22 23:57:00.516268

"""

# revision identifiers, used by Alembic.
revision = '1d6ddd54e6ae'
down_revision = '303383e2e457'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
