"""empty message

Revision ID: 2bfd697dbd29
Revises: b2bf4a90815
Create Date: 2015-04-26 15:22:57.135828

"""

# revision identifiers, used by Alembic.
revision = '2bfd697dbd29'
down_revision = 'b2bf4a90815'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
