"""empty message

Revision ID: 4ec511dac1a4
Revises: 191effdd8583
Create Date: 2015-05-01 12:05:20.315142

"""

# revision identifiers, used by Alembic.
revision = '4ec511dac1a4'
down_revision = '191effdd8583'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    ### end Alembic commands ###
