"""empty message

Revision ID: 50712ef011e6
Revises: 19095257d787
Create Date: 2015-05-02 14:31:53.130935

"""

# revision identifiers, used by Alembic.
revision = '50712ef011e6'
down_revision = '19095257d787'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
