"""empty message

Revision ID: b2bf4a90815
Revises: 16e3df8dd45e
Create Date: 2015-04-26 15:15:50.040898

"""

# revision identifiers, used by Alembic.
revision = 'b2bf4a90815'
down_revision = '16e3df8dd45e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
